import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Router, useRouter} from 'next/router'

export default function Home() {

const router = useRouter()

const handleClick = () => {
  console.log('Placing you order')


  router.push('/product')
}


  return (
    <div className={styles.container}>
      <Head>
        <title>Next Tutorial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Link href='/blog'>
        <a> Blog</a>
        
        </Link>
        <Link href='/product'>
        <a> Products</a>
        
        </Link>
        <Link href='/users'>
        <a> Users</a>
        
        </Link>
        <Link href='/posts'>
        <a> Posts</a>
        
        </Link>

        <button onClick={handleClick}>
          Place Order
        </button>
        <div>
          <h1>Next JS pre-rendering
            
          </h1>
        </div>
      </main>

      
    </div>
  )
}
